version: '3.9'

services:
  storeevent-db:
    image: postgres:15
    container_name: storeevent-db
    restart: always
    environment:
      POSTGRES_DB: storeEvent
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - storeevent_data:/var/lib/postgresql/data

  query-db:
    image: postgres:15
    container_name: query-db
    restart: always
    environment:
      POSTGRES_DB: query
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - query_data:/var/lib/postgresql/data

volumes:
  storeevent_data:
  query_data:
